hmcts/ccd-case-activity-api

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDM-2268
Reduce number of instances from 2 to 1 for all envs apart from `demo`, `prod`, `aat` and `sprod`.
```
[ ] Yes
[x] No
```

RDM-2268: Reduce default capacity

---

infrastructure/outputs.tf
infrastructure/variables.tf

change_default_activity_parameters_values
```
[ ] Yes
[ x] No
```

change_default_activity_parameters_values

---

infrastructure/aat.tfvars

update aat idam url
```
[ ] Yes
[x ] No
```

update aat idam url

---

infrastructure/main.tf

set correct params for prod

---

infrastructure/aat.tfvars

https://tools.hmcts.net/jira/browse/RDM-2723
Update AAT config to use SIDAM
Comment out AAT config for tactical IDAM
```
[ ] Yes
[x] No
```

RDM-2723: Switch AAT to SIDAM

---

infrastructure/aat.tfvars

RDM-2723
Point AAT and Preview back to Tactical IDAM
```
[ ] Yes
[x] No
```

RDM-2723: Revert to Tactical IDAM

---

infrastructure/aat.tfvars

Reverts hmcts/ccd-case-activity-api#49

RDM-2723: Switch to SIDAM

---

infrastructure/aat.tfvars

Reverts hmcts/ccd-case-activity-api#54

RDM-2723: Switch to back to TIDAM

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDM-2484
We don't actually make use of the vault in this app. So an easy removal.
```
[ ] Yes
[x] No
```

[PREVIEW] Remove Hashicorp vault

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDM-2635
Leave aat, prod and demo on current ASP
Shared for the rest
Minor cleanup
```
[ ] Yes
[x] No
```

[PREVIEW] Shared App Service Plan

---

infrastructure/main.tf

/site - 300M
/LogFiles - 400M
https://tools.hmcts.net/jira/browse/RDM-2366
```
[X] Yes
[ ] No
```

Set local cache to 700 MB

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDM-3592
```
[ ] Yes
[ ] No
```

Lock Terrafrom AzureRM provider to 1.19.0

---

.travis.yml
Jenkinsfile_CNP
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-2745
```
[ ] Yes
[ ] No
```

Add 'yarn check' to build

---

.travis.yml
package.json

https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[ ] No
```

Set minimum yarn version

---

.dockerignore
.gitignore
Dockerfile
acb.tpl.yaml

https://tools.hmcts.net/jira/browse/CNP-1131
This PR leverages on layers re-use to reduce the the docker image build time in CI. However, this project using a specific branch of the Jenkins pipeline, **it will have an effect only if you use the latest version of the Jenkins library**.

cnp-1131-acr-tasks

---

app.js
app/job/store-cleanup-job.js
app/routes/add-activity.js
app/routes/get-activities.js
app/user/auth-checker-user-only-filter.js
app/user/roles-based-authorizer.js
app/util/delayed.js
package.json
test/e2e/store-cleanup-end-to-end-test.spec.js
yarn.lock

Bump eslint-config-airbnb-base from 12.1.0 to 13.1.0 + fixes

---

infrastructure/saat.tfvars

Update SAAT with Sidam

---

infrastructure/saat.tfvars

Reverts hmcts/ccd-case-activity-api#124

Revert "Update SAAT with Sidam"

---

Jenkinsfile_CNP
app/redis/redis-client.js
charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/requirements.yaml
charts/ccd-case-activity-api/values.aat.template.yaml
charts/ccd-case-activity-api/values.template.yaml

Cleaned up Helm chart implementation

---

package.json
sonar-project.properties

Sonar config was in the package.json. Moving it to a config file
```
[ ] Yes
[ x] No
```

moved sonar conf to config file

---

Dockerfile
acb.tpl.yaml

RDM-5330-update ccd to use new docker registry url

---

charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/requirements.yaml
charts/ccd-case-activity-api/values.preview.template.yaml
charts/ccd-case-activity-api/values.yaml

RDM-5309- Update Chart format for new AKS cluster

---

charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/requirements.yaml

Bumping base chart

---

app.js
web.config

https://tools.hmcts.net/jira/browse/RDM-5533
Disable `X-Powered-By` header
```
[ ] Yes
[x] No
```

RDM-5533 Disable X-Powered-By header

---

.travis.yml
Dockerfile
infrastructure/main.tf
package.json

https://tools.hmcts.net/jira/browse/RDM-3593
Update project to use node 12.x
```
[ ] Yes
[x] No
```

RDM-3593 - Update to node 12.x

---

.travis.yml
Dockerfile
infrastructure/main.tf
package.json

See #167 
```
[ ] Yes
[x] No
```

RDM-3593 - Update to node 12.x - MASTER

---

Dockerfile

AB#796
Changing the Docker base image to to use alpine-lts-10
```
[x ] Yes
[ ] No
```

Case activity api to prod/base image alpine

---

package.json
yarn.lock

RDM-2508-Rm-nsp

---

charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/requirements.yaml

moving to latest nodejs chart

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/ithc.tfvars
infrastructure/main.tf
infrastructure/outputs.tf
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

Cleaning up terraform

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/RDM-7650
```
[ ] Yes
[x] No
```

RDM-7650 use JSON Def file functionality in befta

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-8393
Update nodejs-healthcheck to 1.6.0
```
[ ] Yes
[X ] No
```

RDM-8393 Update nodejs-healthcheck to 1.6.0

---

Jenkinsfile_CNP

Update Jenkinsfile_CNP rm installCharts

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDM-8995
Adding PR-575 of Definition-Store for develop branch only.
```
[ ] Yes
[x] No
```

CCD Apps Not Working Develop-to-Develop on Preview

---

infrastructure/main.tf

bump tf provider to sort redis issue

---

Jenkinsfile_CNP

RDM-9236
autowire fta dependencies
```
[ ] Yes
[X] No
```

autowire fta dependencies

---

Jenkinsfile_CNP

RDM-9236
autowire fta dependencies
```
[ ] Yes
[X] No
```

pick aat for master builds

---

Jenkinsfile_CNP
aat/build.gradle
aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java

enhance pipeline logic per build type + befta fw upgrade with added imports of definitions
```
[ ] Yes
[X] No
```

enhance pipeline logic per build type

---

aat/src/resources/features/F-000/F-000.feature
aat/src/resources/features/F-000/S-000.td.json
aat/src/resources/features/F-018/F-018.feature
aat/src/resources/features/F-018/F-018_Test_Data_Base.td.json
aat/src/resources/features/F-018/S-001.td.json
aat/src/resources/features/F-018/S-002.td.json
aat/src/resources/features/F-018/S-003.td.json
aat/src/resources/features/F-018/S-004.td.json
aat/src/resources/features/F-018/S-005.td.json
aat/src/resources/features/F-018/S-014-Verification-call.td.json
aat/src/resources/features/common/Case_Creation_Data_Base.td.json
aat/src/resources/features/common/Standard_Full_Case_Creation_Data.td.json
aat/src/resources/features/common/Standard_Token_Creation_Data_For_Case_Creation.td.json

https://tools.hmcts.net/jira/browse/RDM-9282
Format Test JSON Data Files - Activity API
```
[ ] Yes
[x] No
```

RDM-9282 - Format Test JSON Data Files - Activity API - initial commit

---

aat/src/resources/features/F-000/F-000.feature
aat/src/resources/features/F-018/F-018.feature

https://tools.hmcts.net/jira/browse/RDM-9534
```
[ ] Yes
[X] No
```

Removing Health checks scenario as smoke tests

---

Jenkinsfile_CNP
aat/build.gradle

align fw version with 20.1

---

Jenkinsfile_CNP

Merge Develop onto Master (Don't Merge Please)

---

charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/values.yaml

https://tools.hmcts.net/jira/browse/RDM-10469
adjust autoscaling
```
[ ] Yes
[X] No
```

adjust autoscaling

---

Jenkinsfile_CNP

change data store develop pr

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDM-10678
[20.4&20.5] Regular CI Maintenance
```
[ ] Yes
[X] No
```

Trigger develop build

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/RDM-11729
```
[ ] Yes
[ ] No
```

RDM-11729: Upgrade Befta version to 6.13.0

---

charts/ccd-case-activity-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDM-12175
Upgrade Java Base Chart Versions
```
[ ] Yes
[X] No
```

RDM-12175 Upgrade Base Chart Versions

---

.github/workflows/scheduled-dummy-commit.yml

RDM-11603, no develop branch protection on this repo
```
[ ] Yes
[ ] No
```

Create scheduled-dummy-commit.yml RDM-11603

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/RDM-9765
Bump up BEFTA Fw version for RDM-9765.
```
[ ] Yes
[X] No
```

RDM-9765 Applying jit pack and befta changes

---

.gitignore
Jenkinsfile_CNP
aat/build.gradle
aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/HighLevelDataSetupApp.java
package.json

https://tools.hmcts.net/jira/browse/CCD-1283
implement high level data setup for automated definition imports
```
[ ] Yes
[x] No
```

implement high level data setup for automated definition imports

---

aat/build.gradle
aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/HighLevelDataSetupApp.java

https://tools.hmcts.net/jira/browse/CCD-1283
tolerate data setup failures and narrow recent import interval
```
[ ] Yes
[x] No
```

tolerate data setup failures and narrow recent import interval

---

Jenkinsfile_CNP
aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-1131
befta-fw update to 8.2.0
```
[ ] Yes
[x] No
```

befta-fw update to 8.2.0

---

.gitignore
Jenkinsfile_nightly
aat/build.gradle
aat/config/fortify-client.properties
aat/gradle/wrapper/gradle-wrapper.properties
package.json

https://tools.hmcts.net/jira/browse/CCD-1580
Integrated Fortify Scan into Nightly Pipelines
```
[ ] Yes
[x] No
```

CCD-1580: Integrate Fortify Scan into Nightly Pipelines

---

Dockerfile
Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CCD-1650
fix for Fortify Issue 14643918 - Dockerfile Misconfiguration: Default User Privilege
```
[ ] Yes
[x] No
```

fix for Fortify Issue 14643918 - Dockerfile Misconfiguration: Default User Privilege

---

aat/src/resources/features/F-018/F-018.feature
package.json

https://tools.hmcts.net/jira/browse/CCD-2344
Temporary Ignore failed tests
```
[ ] Yes
[x] No
```

CCD-2344 temporary Ignore failed tests

---

.travis.yml
Dockerfile
package.json

https://tools.hmcts.net/jira/browse/CCD-2344
Upgrade nodejs library version to resolve build failures
```
[ ] Yes
[x] No
```

CCD-2344 upgrade nodejs engine library to resolve build issues

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```

Update to build.gradle

---

aat/build.gradle

CCD-2543 (https://tools.hmcts.net/jira/browse/CCD-2543)
Temporarily changed fortifyScan task in build.gradle so that it ignores the results of the scan.
```
[ ] Yes
[x] No
```

CCD-2543: Ignore Fortify scan results

---

charts/ccd-case-activity-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```

helm chart update

---

charts/ccd-case-activity-api/Chart.yaml
charts/ccd-case-activity-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CCD-3362
AKS is failing in Preview Env. Updating redis version in case activity api
```
[ ] Yes
[x] No
```

CCD-3362 update redis version

---

aat/build.gradle
charts/ccd-case-activity-api/Chart.yaml

update comment in build.gradle

---

Jenkinsfile_CNP

CCD-3647 (https://tools.hmcts.net/jira/browse/CCD-3647)
- Added definitionStoreDevelopPr variable to Jenkinsfile_CNP to be consistent with other projects.
- Changed CCD_DATA_STORE_API_BASE_URL and DEFINITION_STORE_URL_BASE URL values used for preview in Jenkinsfile_CNP to https.  Changed DEFINITION_STORE_URL_BASE value to use definitionStoreDevelopPr variable.
```
[ ] Yes
[x] No
```

CCD-3647: Fix preview deploy issues

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-3802
Update to fortify-client version
```
[ ] Yes
[ x] No
```

CCD-3802 Update to fortify-client version

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CCD-4337
CCD-4337 : updated package versions
```
[ ] Yes
[X] No
```

CCD-4337 : updated package versions

---

app/app-insights/app-insights.js

Set App Insights sample rate to 1%

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/CCD-4733
CCD Upgrade from Redis 4 to 6
```
[x] Yes
[] No
```

CCD-4733 CCD Upgrade from Redis 4 to 6

---

package.json
yarn.lock

CCD-5319
Bumped express to 4.19.2
```
[ ] Yes
[X] No
```

CCD-5319 : Fix-CVE-2024-29041 / rebuild

---

package.json
yarn.lock

v3 is broke
https://github.com/microsoft/ApplicationInsights-node.js/issues/1352

CCD-5968 Downgrade ccd-case-activity-api Appinsights again

---

aat/build.gradle

NA
Fix jitpack error 
```
[ ] Yes
[X] No
```

Fix jitpack jar not found error

---

aat/build.gradle
infrastructure/main.tf
infrastructure/state.tf

https://tools.hmcts.net/jira/browse/CME-309
```
[ ] Yes
[x ] No
```

CME-309: Update azurerm

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-6049
CCD-6049 : Bump ccd-test-definitions and befta-fw to latest
```
[ ] Yes
[X] No
```

CCD-6049 : Bump ccd-test-definitions and befta-fw to latest

---

Jenkinsfile_CNP
charts/ccd-case-activity-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CCD-6527
CCD-6527 :: add-reports
```
[ ] Yes
[X] No
```

CCD-6527 :: add-reports
